### ISSUE TITLE
Lakka shows black screen on BananaPI

### ISSUE THREAD

**Issue by digitalLumberjack** [lakkatv/Lakka#131] opened 2014-10-02 07:37 UTC
I build the lastest release of Lakka and i have display issues : 
on a 1600*900 res : a black screen from menu "Settings" to "cave story" with no logo
on a 1920*1200 res : a black screen on all menus, but with logos

**Comment by Kivutar** [comment] 2015-01-05 01:56
I close this as duplicate of #103

**Closed by Kivutar** 2015-01-05 01:56 UTC
