### ISSUE TITLE
Cubox-i: Neo Geo Section

### ISSUE THREAD

**Issue by ralias** [lakkatv/Lakka#156] opened 2015-01-15 07:57 UTC
I didn't found a Neo Geo Section for the original Neo Geo not the pocket. I know that FBA is compatible with NeoGeo but I see all the roms mixed in the same section CPS1/CPS2/Arcade/Neo Geo... When I browse the section looking for a game until I found it I must to go down a lot of time. I think is more useful if we separate it. Will be a good improvement.. Thanks.

**Comment by Kivutar** [comment] 2015-01-15 12:45
Yes, same happens with SEGA cores. I agree that it is a problem.
This bug is a duplicate of this one https://github.com/lakkatv/Lakka/issues/111 so I close it

**Closed by Kivutar** 2015-01-15 12:45 UTC
